//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaktiImProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Vakti_Im_Entities : DbContext
    {
        public Vakti_Im_Entities()
            : base("name=Vakti_Im_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ADRESA> ADRESAs { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<GATIM> GATIMs { get; set; }
        public virtual DbSet<KATEGORI> KATEGORIs { get; set; }
        public virtual DbSet<POROSI> POROSIs { get; set; }
        public virtual DbSet<POROSI_ITEM> POROSI_ITEM { get; set; }
    
        public virtual ObjectResult<Detaje_porosie_Result> Detaje_porosie(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Detaje_porosie_Result>("Detaje_porosie", idParameter);
        }
    
        public virtual ObjectResult<GatimeAktive_Result> GatimeAktive()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GatimeAktive_Result>("GatimeAktive");
        }
    
        public virtual ObjectResult<Porosit_e_bera_Result> Porosit_e_bera(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Porosit_e_bera_Result>("Porosit_e_bera", idParameter);
        }
    
        public virtual ObjectResult<Porosite_e_mia_Result> Porosite_e_mia(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Porosite_e_mia_Result>("Porosite_e_mia", idParameter);
        }
    
        public virtual ObjectResult<Procedure1_Result> Procedure1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure1_Result>("Procedure1");
        }
    
        public virtual ObjectResult<ShfaqPorosi1_Result> ShfaqPorosi1()
        {
            
            
                return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShfaqPorosi1_Result>("ShfaqPorosi1");
            
            
        }
    
        public virtual ObjectResult<ShfaqPorosit0_Result> ShfaqPorosit0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShfaqPorosit0_Result>("ShfaqPorosit0");
        }
    }
}
